Repository AY2021S1-CS2103T-W11-3/tp, pull requests merged in 2020-10, with the labels that each got.

#28 Update dg - target user profile, user stories and use cases
  docs/DeveloperGuide.md
Labels: priority.High

#52 Fix typo in index.md
  docs/index.md
Labels: priority.Medium

#50 Replace Phone class to Weight class
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/day/Day.java
  src/main/java/seedu/address/model/day/Phone.java
  src/main/java/seedu/address/model/day/Weight.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditDayDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/day/DayTest.java
  src/test/java/seedu/address/model/day/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/day/PhoneTest.java
  src/test/java/seedu/address/model/day/WeightTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDayTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Story

#54 UI modifications
  src/main/java/seedu/address/ui/DayCard.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/ArmyTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: UI, priority.High

#61 Added tests for Input and TotalCalories
  src/main/java/seedu/address/model/day/Day.java
  src/main/java/seedu/address/model/day/calorie/Input.java
  src/main/java/seedu/address/ui/DayCard.java
  src/test/java/seedu/address/model/day/DayTest.java
  src/test/java/seedu/address/model/day/calorie/InputTest.java
Labels: priority.Medium

#82 Delete unused classes- address, email
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/day/Address.java
  src/main/java/seedu/address/model/day/Date.java
  src/main/java/seedu/address/model/day/Email.java
  src/main/java/seedu/address/storage/JsonAdaptedInput.java
  src/main/java/seedu/address/storage/JsonAdaptedOutput.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditDayDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/day/AddressTest.java
  src/test/java/seedu/address/model/day/EmailTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDayTest.java
  src/test/java/seedu/address/testutil/DayUtil.java
  src/test/java/seedu/address/testutil/EditDayDescriptorBuilder.java
Labels: priority.High, type.task

#85 Add calorie manager
  src/main/java/seedu/address/logic/commands/CalorieCommand.java
  src/main/java/seedu/address/logic/parser/CalorieCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/day/Day.java
  src/main/java/seedu/address/model/day/calorie/CalorieManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCalorieManager.java
  src/main/java/seedu/address/storage/JsonAdaptedDay.java
  src/main/java/seedu/address/ui/DayCard.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/day/DayTest.java
  src/test/java/seedu/address/model/day/calorie/CalorieManagerTest.java
  src/test/java/seedu/address/testutil/CalorieBuilder.java
  src/test/java/seedu/address/testutil/DayBuilder.java
  src/test/java/seedu/address/testutil/TypicalCalories.java
Labels: priority.Medium, type.task

#99 Update documentation for Stats functionality
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  docs/images/helpMessage.png
  docs/images/weight_stats_chart.png
Labels: documentation, priority.Medium

#101 Update ug and dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: documentation, priority.High

#107 Fix missing heading for User Guide
  docs/UserGuide.md
Labels: bug, documentation

#94 Create a profile
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CalorieCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreateCommandParser.java
  src/main/java/seedu/address/logic/parser/MyFitnessBuddyParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/MyFitnessBuddy.java
  src/main/java/seedu/address/model/ReadOnlyMyFitnessBuddy.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/day/Day.java
  src/main/java/seedu/address/model/person/Height.java
  src/main/java/seedu/address/model/person/ID.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Profile.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/exceptions/DuplicatePersonException.java
  src/main/java/seedu/address/model/person/exceptions/PersonNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/MyFitnessBuddyParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/MyFitnessBuddyTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/person/HeightTest.java
  src/test/java/seedu/address/model/person/IdTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/ProfileTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/MyFitnessBuddyBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalDays.java
Labels: priority.High

#114 Assertion and Logging
  src/main/java/seedu/address/storage/JsonAdaptedDay.java
  src/main/java/seedu/address/storage/JsonAdaptedInput.java
  src/main/java/seedu/address/storage/JsonAdaptedOutput.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
Labels: tP.ProgressTask

#116 Add logging
  src/main/java/seedu/address/ui/DayListPanel.java
Labels: tP.ProgressTask

#113 Assertions, refactoring and logging
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/CalorieCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/MyFitnessBuddy.java
  src/main/java/seedu/address/model/ReadOnlyMyFitnessBuddy.java
  src/main/java/seedu/address/model/person/Height.java
  src/main/java/seedu/address/model/person/ID.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Profile.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/MyFitnessBuddyTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/person/HeightTest.java
  src/test/java/seedu/address/model/person/IdTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: tP.ProgressTask

#117 Updated UGDG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#110 Update DG for Remove Calorie Command and Update Model Diagram
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/RemoveCalorieSequenceDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/RemoveCalorieSequenceDiagram.png
  src/main/java/seedu/address/model/day/UniqueDayList.java
  src/main/java/seedu/address/model/day/calorie/CalorieManager.java
  src/main/java/seedu/address/model/day/calorie/Exercise.java
  src/main/java/seedu/address/model/day/calorie/Food.java
  src/test/java/seedu/address/model/day/calorie/ExerciseTest.java
  src/test/java/seedu/address/model/day/calorie/FoodTest.java
Labels: documentation

#119 Critical Bug Fixes
  src/main/java/seedu/address/model/MyFitnessBuddy.java
  src/test/java/seedu/address/testutil/TypicalDays.java
Labels: bug, priority.High

#103 Sort Day list and CalorieManager list
  src/main/java/seedu/address/model/day/Date.java
  src/main/java/seedu/address/model/day/Day.java
  src/main/java/seedu/address/model/day/UniqueDayList.java
  src/main/java/seedu/address/model/day/calorie/CalorieManager.java
  src/main/java/seedu/address/model/day/calorie/Input.java
  src/main/java/seedu/address/model/day/calorie/Output.java
  src/main/java/seedu/address/model/day/calorie/Time.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: enhancement, priority.Medium

#89 View statistics function
  build.gradle
  src/main/java/seedu/address/model/day/UniqueDayList.java
  src/main/java/seedu/address/ui/CalorieStatsWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/WeightStatsWindow.java
  src/main/resources/images/stats_icon.png
  src/main/resources/view/CalorieStatsWindow.fxml
  src/main/resources/view/DarkChartTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/WeightStatsWindow.fxml
Labels: UI, priority.High

#124 Fix bug where calorie data reset to 0 after editing
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: bug, priority.High

#122 Stats command to view statistics
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/StatsCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MyFitnessBuddyParser.java
  src/main/java/seedu/address/logic/parser/StatsCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/StatsCommandTest.java
  src/test/java/seedu/address/logic/parser/MyFitnessBuddyParserTest.java
  src/test/java/seedu/address/logic/parser/StatsCommandParserTest.java
Labels: UI, priority.High

#129 Update ug - clear command, intro, purpose, audience
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#135 Calorie lists bug - clear and delete commands
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/StatsCommandTest.java
Labels: bug, priority.High

#136 Fix window size
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#137 Change title size and color to white
  src/main/resources/view/ArmyTheme.css
  src/main/resources/view/CalorieInputListPanel.fxml
  src/main/resources/view/CalorieOutputListPanel.fxml
  src/main/resources/view/PersonListPanel.fxml
Labels: UI, priority.High

#132 Chart UI/UX Improvements
  src/main/java/seedu/address/ui/CalorieStatsWindow.java
  src/main/java/seedu/address/ui/HoveredCalorieNode.java
  src/main/java/seedu/address/ui/HoveredWeightNode.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/WeightStatsWindow.java
  src/main/resources/view/CalorieStatsWindow.fxml
  src/main/resources/view/DarkChartTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/WeightStatsWindow.fxml
Labels: UI, hacktoberfest-accepted, priority.Medium

#138 Bug fix for test case
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/MyFitnessBuddy.java
  src/main/java/seedu/address/model/day/exceptions/DuplicateDayException.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/MyFitnessBuddyTest.java
  src/test/java/seedu/address/model/day/DayTest.java
  src/test/java/seedu/address/model/day/UniqueDayListTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDayTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalDays.java
  src/test/java/seedu/address/testutil/TypicalProfiles.java
Labels: bug

#139 Update profile command
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/MyFitnessBuddyParser.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
Labels: enhancement, priority.Medium

#128 Change calorie
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CalorieCommand.java
  src/main/java/seedu/address/logic/commands/ChangeCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/parser/CalorieCommandParser.java
  src/main/java/seedu/address/logic/parser/ChangeCommandParser.java
  src/main/java/seedu/address/logic/parser/MyFitnessBuddyParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
  src/main/java/seedu/address/model/calorie/Calorie.java
  src/main/java/seedu/address/model/calorie/CalorieCount.java
  src/main/java/seedu/address/model/calorie/CalorieManager.java
  src/main/java/seedu/address/model/calorie/Exercise.java
  src/main/java/seedu/address/model/calorie/Food.java
  src/main/java/seedu/address/model/calorie/Input.java
  src/main/java/seedu/address/model/calorie/Output.java
  src/main/java/seedu/address/model/calorie/Time.java
  src/main/java/seedu/address/model/day/UniqueDayList.java
  src/test/java/seedu/address/logic/commands/CalorieCommandTest.java
  src/test/java/seedu/address/logic/parser/CalorieCommandParserTest.java
  src/test/java/seedu/address/model/calorie/CalorieManagerTest.java
  src/test/java/seedu/address/testutil/TypicalDays.java
Labels: priority.Medium, tP.ProgressTask

#133 Storage updates
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/MyFitnessBuddy.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/calorie/CalorieCount.java
  src/main/java/seedu/address/model/calorie/Exercise.java
  src/main/java/seedu/address/model/calorie/Food.java
  src/main/java/seedu/address/model/calorie/Time.java
  src/main/java/seedu/address/model/day/Day.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCalorieManager.java
  src/main/java/seedu/address/storage/JsonAdaptedDay.java
  src/main/java/seedu/address/storage/JsonAdaptedInput.java
  src/main/java/seedu/address/storage/JsonAdaptedOutput.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedProfile.java
  src/main/java/seedu/address/storage/JsonMyFitnessBuddyStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableMyFitnessBuddy.java
  src/main/java/seedu/address/storage/MyFitnessBuddyStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/day/DayTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDayTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInputTest.java
  src/test/java/seedu/address/storage/JsonAdaptedOutputTest.java
  src/test/java/seedu/address/storage/JsonMyFitnessBuddyStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableMyFitnessBuddyTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, type.Storage

#143 add feature to change between different people
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/parser/LoginCommandParser.java
  src/main/java/seedu/address/logic/parser/MyFitnessBuddyParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/MyFitnessBuddy.java
  src/main/java/seedu/address/model/ReadOnlyMyFitnessBuddy.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/ui/DayCard.java
  src/main/java/seedu/address/ui/DayListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DayListCard.fxml
  src/main/resources/view/DayListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CalorieCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/MyFitnessBuddyTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableMyFitnessBuddyTest.java
Labels: priority.Medium

#145 Add labels to day when day is clicked
  src/main/java/seedu/address/ui/CalorieInputListPanel.java
  src/main/java/seedu/address/ui/CalorieOutputListPanel.java
  src/main/java/seedu/address/ui/DayCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarDaySelected.java
  src/main/resources/view/ArmyTheme.css
  src/main/resources/view/CalorieInputListPanel.fxml
  src/main/resources/view/CalorieOutputListPanel.fxml
  src/main/resources/view/DayListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatusBarDaySelected.fxml
Labels: UI, priority.High

#144 Validity of ID
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/model/person/ID.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/model/person/IdTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/ProfileTest.java
  src/test/java/seedu/address/testutil/TypicalProfiles.java
Labels: enhancement

#149 Add profile panels to UI
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProfileCard.java
  src/main/java/seedu/address/ui/ProfileCardPanel.java
  src/main/java/seedu/address/ui/ProfileListPanel.java
  src/main/resources/view/ArmyTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ProfileCardPanel.fxml
  src/main/resources/view/ProfileListCard.fxml
  src/main/resources/view/ProfileListPanel.fxml
Labels: UI, priority.Medium

#150 UG update for Day commands
  docs/UserGuide.md
  docs/images/AddDay.png
  docs/images/DeleteDay.png
  docs/images/EditDay.png
  src/main/java/seedu/address/model/person/ID.java
Labels: documentation

#151 update ug
  docs/UserGuide.md
Labels: documentation

#153 UG
  docs/UserGuide.md
  docs/images/logo.png
Labels: documentation

#152 Update ug for my section
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/chart_menu_bar.png
Labels: documentation

#154 Change UI icon
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/MyFitnessBuddy_icon.png
  src/main/resources/images/address_book_32.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: UI

#158 Update UG to include chart improvements
  docs/UserGuide.md
  docs/images/calorie_stats_chart.png
  docs/images/weight_stats_chart.png
Labels: documentation

#159 Storage update
  src/main/java/seedu/address/model/MyFitnessBuddy.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonMyFitnessBuddyStorage.java
  src/main/java/seedu/address/storage/JsonSerializableMyFitnessBuddy.java
Labels: enhancement

#161 Fix multiple bugs in UI
  build.gradle
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProfileCardPanel.java
  src/main/java/seedu/address/ui/ProfileListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/StatsCommandTest.java
Labels: UI, bug

#211 Bug fix : #210 Java Integer Overflow
  src/main/java/seedu/address/logic/commands/CalorieCommand.java
Labels: bug
