Repository AY2021S1-CS2103T-W11-3/tp, pull requests merged in 2020-11, with the labels that each got.

#213 Add view command for displaying calorie lists
  docs/UserGuide.md
  docs/images/day_clicked.png
  docs/images/day_viewed.png
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/MyFitnessBuddyParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/ui/DayCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/StatsCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: priority.High, type.FeatureFlaw

#228 Ethan ppp
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/team/ethanso56.md
Labels: documentation

#229 Add PPP draft
  docs/team/junhui-phoon.md
Labels: documentation

#231 Ethan ppp
  docs/team/ethanso56.md
Labels: documentation

#233 Updating storage tests
  src/main/java/seedu/address/model/day/UniqueDayList.java
  src/main/java/seedu/address/model/person/Height.java
  src/main/java/seedu/address/storage/JsonAdaptedCalorieManager.java
  src/main/java/seedu/address/storage/JsonAdaptedDay.java
  src/main/java/seedu/address/storage/JsonAdaptedInput.java
  src/main/java/seedu/address/storage/JsonAdaptedOutput.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedProfile.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCalorieManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDayTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInputTest.java
  src/test/java/seedu/address/storage/JsonAdaptedOutputTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedProfileTest.java
  src/test/java/seedu/address/testutil/CalorieManagerBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalCalorieManager.java
  src/test/java/seedu/address/testutil/TypicalDays.java
  src/test/java/seedu/address/testutil/TypicalPerson.java
  src/test/java/seedu/address/testutil/TypicalProfiles.java
Labels: type.CodeCoverage

#232 update dg
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/ViewSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/ViewCommand.java
Labels: documentation

#242 More test cases
  src/main/java/seedu/address/model/MyFitnessBuddy.java
  src/main/java/seedu/address/model/calorie/CalorieManager.java
  src/main/java/seedu/address/storage/JsonAdaptedCalorieManager.java
  src/main/java/seedu/address/storage/JsonSerializableMyFitnessBuddy.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonMyFitnessBuddyStorageTest/invalidAndValidPersonMyFitnessBuddy.json
  src/test/data/JsonMyFitnessBuddyStorageTest/invalidPersonMyFitnessBuddy.json
  src/test/data/JsonMyFitnessBuddyStorageTest/notJsonFormatMyFitnessBuddy.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableMyFitnessBuddyTest/anotherPersonsMyFitnessBuddy.json
  src/test/data/JsonSerializableMyFitnessBuddyTest/duplicatePersonMyFitnessBuddy.json
  src/test/data/JsonSerializableMyFitnessBuddyTest/invalidPersonMyFitnessBuddy.json
  src/test/data/JsonSerializableMyFitnessBuddyTest/typicalPersonsMyFitnessBuddy.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CalorieCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/MyFitnessBuddyTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCalorieManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonMyFitnessBuddyStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableMyFitnessBuddyTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalDays.java
  src/test/java/seedu/address/testutil/TypicalPerson.java
  src/test/java/seedu/address/testutil/TypicalProfiles.java
Labels: type.CodeCoverage

#234 Multiple Bug Fixes
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/ui/CommanderBmiStatsWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProfileCardPanel.java
  src/main/java/seedu/address/ui/ProfileListPanel.java
  src/main/resources/view/MainWindow.fxml
Labels: bug

#246 Fix Sample Data bug
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.FunctionalityBug

#240 Update User Guide / Developer Guide
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddDaySequence.puml
  docs/diagrams/StatsSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UiClassDiagram1.puml
  docs/diagrams/UiClassDiagram2.puml
  docs/diagrams/UiClassDiagram3.puml
  docs/diagrams/UiClassDiagram4.puml
  docs/diagrams/UiClassDiagram5.puml
  docs/diagrams/UiClassDiagram6.puml
  docs/diagrams/WeightChartActivityDiagram.puml
  docs/images/AddDaySequence.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/StatsSequenceDiagram.png
  docs/images/Ui.png
  docs/images/UiClassDiagram1.png
  docs/images/UiClassDiagram2.png
  docs/images/UiClassDiagram3.png
  docs/images/UiClassDiagram4.png
  docs/images/UiClassDiagram5.png
  docs/images/UiClassDiagram6.png
  docs/images/WeightChartActivityDiagram.png
  docs/images/find_bmi.png
  docs/images/login_example.png
  docs/images/overall_progress_chart.png
  docs/images/starting_screen.png
  docs/index.md
Labels: documentation

#251 update ug
  docs/UserGuide.md
  docs/images/dayAfterView.png
  docs/images/dayBeforeView.png
  docs/images/day_viewed.png
Labels: documentation

#256 Fix UML diagrams
  docs/diagrams/AddDaySequence.puml
  docs/diagrams/StatsSequenceDiagram.puml
  docs/images/AddDaySequence.png
  docs/images/StatsSequenceDiagram.png
Labels: documentation

#263 Fix storage bug
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.FunctionalityBug, type.Storage

#265 Developer guide
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/calorieImages/CalorieBudget.png
  docs/images/calorieImages/getCurrentBmi().png
  docs/images/calorieImages/getProgress().png
Labels: documentation

#244 Branch ugdg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CreateProfileSequenceDiagram.puml
  docs/diagrams/LoginActivityDiagram.puml
  docs/diagrams/UpdateProfileSequenceDiagram.puml
  docs/images/CreateProfile.png
  docs/images/CreateProfileSequenceDiagram.png
  docs/images/LoginActivityDiagram.png
  docs/images/LoginProfile.png
  docs/images/UpdateProfile.png
  docs/images/UpdateProfileSequenceDiagram.png
  docs/team/jiaax.md
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/model/MyFitnessBuddy.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Profile.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedProfile.java
  src/main/java/seedu/address/ui/ProfileCard.java
  src/test/java/seedu/address/model/person/ProfileTest.java
  src/test/java/seedu/address/storage/JsonAdaptedProfileTest.java
  src/test/java/seedu/address/testutil/UpdateProfileDescriptorBuilder.java
Labels: documentation

#260 More test cases
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/parser/LoginCommandParser.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/TypicalDays.java
  src/test/java/seedu/address/testutil/TypicalPerson.java
Labels: type.CodeCoverage
